version: '3'

services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        hostname: gitlab
        volumes:
            - ./gitlab/config:/etc/gitlab
            - ./gitlab/data:/var/opt/gitlab
            - ./gitlab/log:/var/log/gitlab
        ports:
            - "8080:80"
            - "2222:22"
    runner:
        image: gitlab/gitlab-runner:latest
        command: run
        volumes:
            - ./runner:/etc/gitlab-runner:ro

